# Generated by Django 4.1.5 on 2023-05-10 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('taste', models.BooleanField(choices=[('sweet', 'sweet'), ('sour', 'sour'), ('salty', 'salty'), ('bitter', 'bitter'), ('savory', 'savory')], max_length=50)),
                ('state', models.CharField(choices=[('mp', 'mp'), ('rajasthan', 'rajasthan'), ('gujrat', 'gujrat'), ('maharashtra', 'maharashtra'), ('odissa', 'odissa'), ('telangana', 'telangana')], max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tea_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('selling_price', models.CharField(max_length=50)),
                ('discounted_price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('tea_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tea_place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registration')),
            ],
        ),
    ]
